title: Law Awareness Weeks @ CDC
url: https://lawawarenessweeks.cdc.gov.sg
favicon: /images/favicon.png
colors:
  primary-color: "#e72753"
  secondary-color: "#e72753"
  media-colors:
    - title: media-color-one
      color: "#212529"
    - title: media-color-two
      color: "#343a40"
    - title: media-color-three
      color: "#495057"
    - title: media-color-four
      color: "#6c757d"
    - title: media-color-five
      color: "#adb5bd"
resources_name: Resources
description: This is an informational site about Law Awareness Weeks @ CDC.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d3mcsrizamdfe0.amplifyapp.com/
prod: https://master.d3mcsrizamdfe0.amplifyapp.com/
is_government: true
facebook-pixel: ""
shareicon: /images/isomer-logo.svg
google_analytics_ga4: G-W97MQYYR3W
linkedin-insights: ""
