title: Law Awareness Weeks @ CDC
url: ""
favicon: /images/favicon-isomer.ico
colors:
  primary-color: "#417505"
  secondary-color: "#00838f"
  media-colors:
    - title: media-color-one
      color: "#49759a"
    - title: media-color-two
      color: "#507c1c"
    - title: media-color-three
      color: "#00838f"
    - title: media-color-four
      color: "#00838f"
    - title: media-color-five
      color: "#00838f"
resources_name: Resources
description: This is an informational site about Law Awareness Weeks @ CDC.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://pa-law-staging.netlify.app
prod: https://pa-law-prod.netlify.app
is_government: true
